version: "1"

name: "dashboard-project"

services:
  dashboard:
    image: ghcr.io/cambio-project/dashboard-vue-23:latest
    ports:
      - 8082:3000
    networks:
      - dashboardNetwork
    pull_policy: always
  pspwizard:
    image: ghcr.io/cambio-project/pspwizardextended:latest
    container_name: pspwizard
    ports:
      - 8080:8080
    networks:
      - dashboardNetwork
    pull_policy: always
  tqproprefiner:
    image: ghcr.io/cambio-project/transient-behavior-requirement-refiner:latest
    container_name: tqproprefiner
    ports:
      - 8084:80
    networks:
      - dashboardNetwork
    pull_policy: always

networks:
  dashboardNetwork:
