version: "1"

name: "dashboard-project"

services:
  dashboard:
    image: ghcr.io/cambio-project/dashboard-vue-23:latest
    ports:
      - 8080:3000
    networks:
      - dashboardNetwork
    pull_policy: always

  pspwizard:
    image: ghcr.io/cambio-project/pspwizardextended:latest
    container_name: pspwizard
    ports:
      - 8081:8080
    networks:
      - dashboardNetwork
    pull_policy: always

  tqproprefiner:
    image: ghcr.io/cambio-project/transient-behavior-requirement-refiner:latest
    container_name: tqproprefiner
    ports:
      - 8082:80
    networks:
      - dashboardNetwork
    pull_policy: always
    volumes:
      - ./data/simulationResults:/simulations_results

  tbverifier:
    image: ghcr.io/cambio-project/transient-behavior-verifier:latest
    container_name: tbverifier
    ports:
      - 8083:5000
    networks:
      - dashboardNetwork
    pull_policy: always
    volumes:
      - ./data/simulationResults:/app/simulationResults

  misim:
    image: ghcr.io/cambio-project/misim:latest
    container_name: misim
    ports:
      - 8084:8080
    networks:
      - dashboardNetwork
    pull_policy: always
    volumes:
      - ./data/simulationResults:/simulations_results

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 8085:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8086:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  dashboardNetwork:
